clear; clc; close all;

run('startup.m')

% parameter
projectName = 'SleepStageHRV';
subID = 'sleepWake';
inputFilePath = ['Data', filesep, 'ECG_Wake.txt'];
outputFolderPath = [pwd, filesep, 'OutputData', filesep, 'ResultsSleepWake'];
fs = 500;

% Remove old files generated by this demo
if exist(outputFolderPath, 'dir')
    rmdir(outputFolderPath, 's');
    fprintf('Old Demo Folder deleted \n');
end

% Initialize settings for demo
HRVparams = InitializeHRVparams(projectName, inputFilePath, outputFolderPath, fs); 

% 1. Load Data
rr = load(HRVparams.readdata);
t = cumsum(rr);

% 2. Analyze RR Data - Using HRV Toolbox Main function
[results, resFilename] = Main_HRV_Analysis(rr,t,'RRIntervals',HRVparams,...
                                                           subID,[]);
